version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: frontend
    ports:
      - '3000:3000'

  mvp-backend:
    image: olegdayo/mvp-backend:8c21474d406815bb9cf61245810818e1a3b6c220
    hostname: mvp-backend
    ports:
      - '8080:8080'
